// Generated by CodiumAI

describe('ExperstiseQuery', () => {

    // Displays an error message if no option is selected from the dropdown list
    it('should display an error message when no option is selected from the dropdown list', () => {
      // Mock the necessary dependencies and setup the initial state
      const navigation = jest.fn();
      const setSelected = jest.fn();
      const setData = jest.fn();
      const setIsLoading = jest.fn();
      const setVisibleModal = jest.fn();
      const axiosGetMock = jest.spyOn(axios, 'get');
      axiosGetMock.mockResolvedValue({ data: [] });
      const wrapper = shallow(<ExperstiseQuery navigation={navigation} />);
  
      // Simulate user interaction by not selecting any option from the dropdown list
      wrapper.find(SelectList).props().setSelected(null);
      wrapper.find(TouchableOpacity).props().onPress();
  
      // Assert that the error message is displayed
      expect(wrapper.find(Text).at(0).props().children).toBe("Veuillez sélectionner une option pour préciser le type d'expertise voulu (à domicile ou à l oavct)");
    });


});
