import { FONT, MARGIN, COLORS, SCREENSIZE } from "../../constants";

const HomeStyle = {
  Page: {
    alignItems: "center",
    justifyContent: "center",
    marginRight: MARGIN.horizontal,
    marginLeft: MARGIN.horizontal,
  },
  colorPage: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  SectionIcon: {
    alignSelf: "flex-end",
    flexDirection: "row",
    paddingTop: 2,
    paddingBottom: 5,
  },
  Icon: {
    color: COLORS.primary,
    paddingLeft: 10,
  },
  ViewButton: {
    flexDirection: "row",
    paddingBottom: 20,
  },
  Section: {
    width: "100%",
    paddingTop: 15,
  },
  SectionSlider: {
    width: "100%",
    paddingTop: 10,
  },
  image: {
    width: 100,
    height: 100,
    marginTop: MARGIN.vertical,
  },
  image2: {
    width: 120,
    height: 100,
    marginTop: MARGIN.vertical,
  },
  avatar: {
    width: 50,
    height: 50,
    marginLeft: 20,
  },
  avatarProfil: {
    width: 150,
    height: 150,
  },
  notification: {
    width: 40,
    height: 40,
  },
  button: {
    width: SCREENSIZE.deviceWidth / 2 - 25,
    height: SCREENSIZE.deviceHeight / 4 - 25,
    backgroundColor: COLORS.secondary,
    borderRadius: 15,
    alignItems: "center",
    marginRight: 20,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: COLORS.primary,
    height: 50,
    marginLeft: MARGIN.vertical,
    marginRight: MARGIN.vertical,
    borderRadius: 10,
  },
  btnDecon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: COLORS.primary,
    height: 50,
    marginLeft: MARGIN.vertical,
    marginRight: MARGIN.vertical,
    borderRadius: 10,
  },
  Text: {
    fontFamily: FONT.PoppinsBold,
    padding: 10,
    fontSize: SCREENSIZE.deviceHeight / 55,
    color: COLORS.buttonText,
    textAlign: "center",
  },
  viewButton: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  imageContainer: {
    borderRadius: 15,
    overFlow: "hidden",
  },
  imageSlider: {
    width: SCREENSIZE.deviceWidth - 25,
    height: 100,
    borderRadius: 15,
  },
  ButtonRetour: {
    color: COLORS.primary,
  },
  flatlist: {
    backgroundColor: "rgba(224, 252, 255, 0.4)",
    borderColor: "#78CAD5",
    borderWidth: 1,
    height: 80,
    width: "90%",
    marginTop: 20,
    alignSelf: "center",
    borderRadius: 10,
    flexDirection: "row",
    paddingLeft: 10,
    alignItems: "center",
  },
  Header: {
    width: "100%",
    flexDirection: "row",
    paddingTop: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnLr: {
    paddingLeft: 10,
  },
  btnRr: {
    paddingRight: 10,
  },
  viewTitle: {
    justifyContent: "center",
  },
  TextHeader: {
    fontFamily: FONT.Black,
    fontSize: 15,
  },
  text: {
    fontFamily: FONT.Black,
    color: COLORS.white,
  },
  viewProfil: {
    width: "100%",
    height: 330,
    marginTop: 30,
    paddingTop: 10,
    backgroundColor: "#F2F2F2",
    borderRadius: 15,
  },
  profilView: {
    paddingBottom: 10,
  },
  btnDecon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: COLORS.primary,
    height: 50,
    marginLeft: MARGIN.vertical,
    marginRight: MARGIN.vertical,
    borderRadius: 10,
  },
  iconProfil: {
    marginLeft: 10,
    marginRight: 10,
    color: COLORS.white,
  },
  imageRenew: {
    marginTop: 20,
    width: 300,
    height: 250,
  },
  textTitleRenew: {
    paddingTop: 20,
    fontFamily: FONT.Black,
    fontSize: 14,
    color: COLORS.primary,
  },
  errorText: {
    color: "red",
    fontFamily: FONT.SfProMedium,
    paddingTop: 2,
  },
  input: {
    height: 48,
    width: "100%",
    backgroundColor: COLORS.secondary,
    padding: MARGIN.horizontal,
    borderRadius: 10,
    fontFamily: FONT.SfProRegular,
  },
  inputDesc: {
    height: 60,
    width: "100%",
    backgroundColor: COLORS.secondary,
    padding: MARGIN.horizontal,
    borderRadius: 10,
    fontFamily: FONT.SfProRegular,
  },
  subtitleForm: {
    paddingTop: 2,
    fontFamily: FONT.SfProRegular,
    fontSize: 14,
    color: COLORS.text,
    textAlign: "center",
  },
  textModalExpertise: {
    paddingTop: 10,
    fontFamily: FONT.SfProMedium,
    fontSize: 14,
    color: COLORS.text,
    textAlign: "center",
  },
  btnForm: {
    backgroundColor: COLORS.primary,
    borderRadius: 5,
    marginVertical: MARGIN.vertical,
    width: 276,
    height: 51,
    padding: MARGIN.vertical,
    alignItems: "center",
  },
  modalBackGround: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    width: "90%",
    height: "60%",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 20,
    elevation: 20,
  },
  modalContainerPayment: {
    width: "90%",
    height: "45%",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 20,
    elevation: 20,
  },
  header: {
    width: "100%",
    height: 40,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  textModal: {
    marginVertical: 5,
    fontSize: 20,
    textAlign: "center",
    fontFamily: FONT.Black,
  },
  textInput: {
    height: 48,
    width: "100%",
    backgroundColor: COLORS.secondary,
    padding: MARGIN.horizontal,
    borderRadius: 10,
    fontFamily: FONT.SfProRegular,
  },
  textBtn: { color: COLORS.white, fontFamily: FONT.Black },
  viewAllInput: { width: "100%", paddingTop: 30 },
  modalBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 5,
    marginVertical: MARGIN.vertical,
    width: 276,
    height: 51,
    padding: MARGIN.vertical,
    alignItems: "center",
  },
  modalBtnPayment: {
    backgroundColor: "#FF0000",
    borderRadius: 5,
    flexDirection: "row",
    marginVertical: MARGIN.vertical,
    width: 276,
    height: 51,
    padding: MARGIN.vertical,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "red",
    fontFamily: FONT.SfProMedium,
    paddingTop: 2,
  },
  iconColor: { color: COLORS.gray },
  eyeBtn: {
    position: "absolute",
    right: 15,
    top: 10,
  },
  centeredView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    padding: 35,
    width: "90%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  imageAlert: {
    height: 60,
    width: 60,
    borderRadius: 50,
  },
  textAlert: {
    fontFamily: FONT.Black,
  },
  textStatus: {
    fontFamily: FONT.SfProMedium,
    fontSize: 13,
    paddingBottom: 3,
    color: COLORS.white,
  },
  viewContent: {
    flexDirection: "column",
    paddingLeft: 10,
  },
  viewCard:{
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(220, 228, 255, 2.85)",
    width: "45%",
    borderRadius:5,
    justifyContent: "center",
    marginRight: 10
  },
  viewCard2:{
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "orange",
    width: "45%",
    borderRadius:5,
    justifyContent: "center",
    marginRight: 10
  },
  cardColum:{
    flexDirection: "row",
    width:"80%"
  },
};

export default HomeStyle;
